#!/bin/bash
python3 -m venv env
source env/bin/activate
pip install flet psycopg[binary] bcrypt
yay -Sy kdialog
sudo apt install kdialog
echo """#!/bin/bash
cd ~/capp
source env/bin/activate
python client.py""" >> capp
mv capp /usr/local/bin
chmod +x /usr/local/bin/capp